---
language: node_js
node_js:
  - "4.2.6"

sudo: false

cache:
  directories:
    - node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - npm config set spin false
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - npm test
