---
dist: trusty
language: node_js
node_js:
  - "6"

addons:
  chrome: stable

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g bower
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  - bower install

script:
  - npm test
